apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: csi-driver
  name: csi-driver
spec:
  selector:
    matchLabels:
      app: csi-driver
  template:
    metadata:
      labels:
        app: csi-driver
    spec:
      containers:
        - name: csi-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/csi-driver.mattslater.io/csi.sock"
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          ports:
            - containerPort: 8080
              name: healthz
          livenessProbe:
            exec:
              command:
                - /csi-node-driver-registrar
                - --kubelet-registration-path=/var/lib/kubelet/plugins/csi-driver.mattslater.io/csi.sock
                - --mode=kubelet-registration-probe
            initialDelaySeconds: 30
            timeoutSeconds: 15
        - name: csi-driver
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: mattslater/csi-driver-linux:v0.1.2
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: pod-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
            - name: storage-dir
              mountPath: /storage-dir
              mountPropagation: Bidirectional
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_SOCKET_PATH
              value: /csi/csi.sock
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi-driver.mattslater.io/
            type: DirectoryOrCreate
        - name: pod-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: storage-dir
          hostPath:
            path: /tmp/csi-driver.mattslater.io
            type: DirectoryOrCreate
