kind: Pod
apiVersion: v1
metadata:
  name: yolo
spec:
  containers:
    - name: test-container
      resources:
        limits:
          memory: 128Mi
          cpu: 500m
      image: busybox:1.28
      volumeMounts:
        - mountPath: "/definition"
          name: my-ephemeral-volume
      command: ["sleep", "1000000"]
  volumes:
    - name: my-ephemeral-volume
      csi:
        driver: csi-driver.mattslater.io
        volumeAttributes:
          csi-driver.mattslater.io/filename: "yolo.txt"
          csi-driver.mattslater.io/data: "you only live once\n"
---
kind: Pod
apiVersion: v1
metadata:
  name: lol
spec:
  containers:
    - name: test-container
      resources:
        limits:
          memory: 128Mi
          cpu: 500m
      image: busybox:1.28
      volumeMounts:
        - mountPath: "/definition"
          name: my-ephemeral-volume
      command: ["sleep", "1000000"]
  volumes:
    - name: my-ephemeral-volume
      csi:
        driver: csi-driver.mattslater.io
        volumeAttributes:
          csi-driver.mattslater.io/filename: "lol.txt"
          csi-driver.mattslater.io/data: "laugh out loud\n"
