kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
spec:
  containers:
    - name: my-frontend
      resources:
        limits:
          memory: 128Mi
          cpu: 500m
      image: busybox:1.28
      volumeMounts:
        - mountPath: "/data"
          name: my-ephemeral-volume
      command: ["sleep", "1000000"]
  volumes:
    - name: my-ephemeral-volume
      csi:
        driver: csi-driver.mattslater.io
        volumeAttributes:
          csi-driver.mattslater.io/filename: "test-file"
          csi-driver.mattslater.io/data: "this is some data"
